### ISSUE TITLE
issue on duplicate index on 

### ISSUE THREAD

**Issue by mdissel** [migajek/ServiceStack.Authentication.Marten#1]
This line is creating a duplicate index DDL exception in Marten. A duplicate field is automatically indexed.
see http://jasperfx.github.io/marten/documentation/documents/customizing/duplicated_fields/

https://github.com/migajek/ServiceStack.Authentication.Marten/blob/master/src/ServiceStack.Authentication.Marten/MartenAuthRepositoryConfig.cs#L29

 ```
CREATE INDEX mt_doc_userauthdetails_idx_user_auth_id ON public.mt_doc_userauthdetails ("user_auth_id");
 
 CREATE INDEX mt_doc_userauthdetails_idx_user_auth_id ON public.mt_doc_userauthdetails ((user_auth_id));
 
```

**Comment by migajek** [comment]
Thank you for the report. Please update to 0.1.2, this should be fixed
I'm not able to verify the fix as the problem didn't occurred on my setup

**Comment by mdissel** [comment]
Thanks!
