### ISSUE TITLE
compile error when referenced by servicestack core 1.0.41

### ISSUE THREAD

**Issue by mdissel** [migajek/ServiceStack.Authentication.Marten#3]
See this thread https://forums.servicestack.net/t/upgrade-to-servicestack-core-1-0-41-add-reference-to-servicestack-interfaces-build-error/4008
Any idea what's causing this?

**Comment by migajek** [comment]
Hi, sorry for the late response. I'll try figuring this out this week. It might be the dependencies being too specific about versions of libraries

**Comment by mdissel** [comment]
i think that updating to the latest servicestack version will fix the issue..The version of servicestack.interfaces has changed in the last update

**Comment by mdissel** [comment]
I tried to create a pull request, but I just removed VS 2015 from my dev machine...

**Comment by migajek** [comment]
this has been fixed now in 0.2.0. please update the reference
